#!/sbin/openrc-run
# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

: ${WIREPROXY_CONFIG:=/etc/wireproxy/${RC_SVCNAME}.conf}

name="wireproxy daemon"
description="Wireguard client as socks5 proxy"
command=/usr/bin/wireproxy
command_args="${wireproxy_args} --config ${WIREPROXY_CONFIG}"
command_background=true
required_files="${WIREPROXY_CONFIG}"
pidfile="/run/${RC_SVCNAME}.pid"

extra_commands="checkconfig"

depend() {
	use net
}

checkconfig() {
	local output=
	local retval=

	output=$(${command} --config "${WIREPROXY_CONFIG}" --configtest 2>&1)
	retval=$?

	if [ ${retval} -ne 0 ]; then
		eerror ${output}
	fi

	eend ${retval} "Config test failed (${WIREPROXY_CONFIG})"
}

start_pre() {
	checkconfig
}
