#!/sbin/openrc-run
# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

: ${FOUNDATIONDB_CONFIG_FILE:=/etc/foundationdb/foundationdb.conf}
: ${FOUNDATIONDB_CLUSTER_FILE:=/etc/foundationdb/fdb.cluster}
: ${FOUNDATIONDB_REMOTE_CLUSTERS:=}

name="FoundationDB process monitor"
description="FoundationDB is a distributed key-value database"

pidfile="/run/foundationdb/${RC_SVCNAME}.pid"

command=/usr/sbin/fdbmonitor
command_user="foundationdb:foundationdb"
command_args="--lockfile ${pidfile}"
command_args_background="--daemonize"

required_files="${FOUNDATIONDB_CONFIG_FILE} ${FOUNDATIONDB_CLUSTER_FILE} ${FOUNDATIONDB_REMOTE_CLUSTERS}"

depend() {
	need net
}

start_pre() {
	checkpath -d -m 0755 -o ${command_user} /etc/foundationdb
	checkpath -d -m 0755 -o ${command_user} /run/foundationdb
	checkpath -d -m 0755 -o ${command_user} /var/lib/foundationdb
	checkpath -d -m 0755 -o ${command_user} /var/log/foundationdb 

	checkpath -m 0644 -o ${command_user} ${FOUNDATIONDB_CONFIG_FILE}
	checkpath -m 0644 -o ${command_user} ${FOUNDATIONDB_CLUSTER_FILE}

	if [ -n "${FOUNDATIONDB_REMOTE_CLUSTERS}" ]; then
		checkpath -m 0644 -o ${command_user} ${FOUNDATIONDB_REMOTE_CLUSTERS}
	fi
}
