#!/sbin/openrc-run

name="vmagent"
description="Victoria Metrics data collector and filtering service"

: ${VM_SCRAPE_CONFIG:=/etc/victoria-metrics/vmagent.yml}
: ${VM_REMOTE_URLS:=http://127.0.0.1:8427/insert/0/prometheus/api/v1/write}
: ${VM_TMP_DATAPATH:=/var/tmp/"${RC_SVCNAME}"}

if yesno "${VM_DISABLE_ON_DISK_QUEUE}"; then 
	unset VM_TMP_DATAPATH
else
	unset VM_DISABLE_ON_DISK_QUEUE
fi

VM_ARGS="
	${VM_TMP_DATAPATH:+-remoteWrite.tmpDataPath=\"${VM_TMP_DATAPATH}\"}
	${VM_DISABLE_ON_DISK_QUEUE:+-remoteWrite.disableOnDiskQueue}
	${VM_SCRAPE_CONFIG:+-promscrape.config=\"${VM_SCRAPE_CONFIG}\"}
	${VM_MEM_ALLOWED_BYTES:+-memory.allowedBytes=\"${VM_MEM_ALLOWED_BYTES}\"}
	${VM_MEM_ALLOWED_PCT:+-memory.allowedPercent=\"${VM_MEM_ALLOWED_PCT}\"}
	${VM_ARGS}
"

for url in ${VM_REMOTE_URLS}; do
	VM_ARGS="${VM_ARGS} -remoteWrite.url=\"${url}\""
done

for url in ${VM_REMOTE_URL_RELABELS}; do
	VM_ARGS="${VM_ARGS} -remoteWrite.urlRelabelConfig=\"${url}\""
done

for url in ${VM_RELABELS}; do
	VM_ARGS="${VM_ARGS} -remoteWrite.relabelConfig=\"${url}\""
done

for addr in ${VM_HTTP_LISTEN_ADDRS}; do
	VM_ARGS="${VM_ARGS} -httpListenAddr=\"${addr}\""
done

command="/usr/bin/vmagent"
command_args="${command_args:-"${VM_ARGS}"}"
command_user="victoria-metrics:victoria-metrics"
supervisor="${supervisor:-supervise-daemon}"

extra_started_commands="reload"
extra_commands="checkconfig"

if [ -z "${output_logger}" ] && [ -z "${output_log+set}" ]; then
	output_log="/var/log/victoria-metrics/${RC_SVCNAME}.log"
fi
if [ -z "${error_logger}" ] && [ -z "${error_log+set}" ]; then
	error_log="/var/log/victoria-metrics/${RC_SVCNAME}.log"
fi

depend() {
	need net
	before vminsert
}

checkconfig() {
	local vm_args=

	if [ -n "${VM_SCRAPE_CONFIG}" ]; then
		if [ ! -r "${VM_SCRAPE_CONFIG}" ]; then
			eerror "$RC_SVCNAME: \`${VM_SCRAPE_CONFIG}' is not readable"
			return 1
		fi
		vm_args="${vm_args} -promscrape.config=${VM_SCRAPE_CONFIG}"
	fi

	if [ -n "${VM_REMOTE_URL_RELABELS}" ]; then
		for url in ${VM_REMOTE_URLS}; do
			vm_args="${vm_args} -remoteWrite.url=\"${url}\""
		done

		for url in ${VM_REMOTE_URL_RELABELS}; do
			vm_args="${vm_args} -remoteWrite.urlRelabelConfig=\"${url}\""
		done
	fi

	if [ -n "${VM_RELABELS}" ]; then
		for url in ${VM_RELABELS}; do
			vm_args="${vm_args} -remoteWrite.relabelConfig=\"${url}\""
		done
	fi

	[ -z "${vm_args}" ] && return 0

	if [ -n "${error_log}" ]; then
		checkpath -q -d -o "${command_user}" "$(dirname "${error_log}")"
	fi

	set -o pipefail

	runuser -u "${command_user%%:*}" -g "${command_user##*:}" -- "${command}" \
		-loggerLevel=FATAL \
		-loggerOutput=stdout \
		-dryRun \
		${vm_args} |\
	runuser -u "${command_user%%:*}" -g "${command_user##*:}" -- tee \
		--append "${error_log:-/dev/stdout}" \
		> /dev/null

	eend $? "${RC_SVCNAME}: invalid configuration, check log file for errors"
}

reload() {
	ebegin "Reloading ${RC_SVCNAME} configuration"
	case "${supervisor}" in
		supervise-daemon)
			supervise-daemon ${RC_SVCNAME} --signal HUP
			;;
		*)
			start-stop-daemon --pidfile "${pidfile}" --signal HUP
			;;
	esac
	eend $?
}

start_pre() {
	checkconfig || return $?

	if [ -n "${VM_TMP_DATAPATH}" ]; then
		checkpath -q -d -o "${command_user}" "${VM_TMP_DATAPATH}"
	fi

	if [ -n "${output_log}" ]; then
		checkpath -q -d -o "${command_user}" "$(dirname "${output_log}")"
	fi

	if [ -n "${error_log}" ]; then
		checkpath -q -d -o "${command_user}" "$(dirname "${error_log}")"
	fi
}
